version: "3.8"

services:
  postgres:
    image: postgres
    container_name: postgres_lab7
    ports:
      - "5432:5432"
    networks:
      - postgres
    volumes:
      - postgres:/data/postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - PGDATA=/data/postgres
      - POSTGRES_DB=lab7

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
